services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/config.yml:/etc/traefik/config.yml:ro
      - ./acme/acme.json:/etc/traefik/acme/acme.json
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--log.level=DEBUG"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${TRAEFIK_DASHBOARD_DOMAIN}"
      - "--experimental.plugins.fail2ban.moduleName=github.com/traefik/plugin-fail2ban"
    labels:
      - "traefik.enable=true"
      # Dashboard configuration
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.tls.options=default"
      # TLS options
      - "traefik.tls.options.default.minversion=${TLS_MIN_VERSION}"
      # Middlewares chain
      - "traefik.http.routers.dashboard.middlewares=auth,headers,rate-limit"
      # Auth middleware
      - "traefik.http.middlewares.auth.basicauth.users=${ADMIN_AUTH}"
      # Rate limit middleware
      - "traefik.http.middlewares.rate-limit.ratelimit.average=${RATE_LIMIT_AVERAGE}"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=${RATE_LIMIT_BURST}"
      # Headers middleware
      - "traefik.http.middlewares.headers.headers.stsSeconds=${STS_SECONDS}"
      - "traefik.http.middlewares.headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.headers.headers.stsPreload=true"
      - "traefik.http.middlewares.headers.headers.forceSTSHeader=true"
      # Fail2Ban middleware
      - "traefik.http.middlewares.fail2ban.plugin.fail2ban.maxretry=${FAIL2BAN_MAXRETRY}"
      - "traefik.http.middlewares.fail2ban.plugin.fail2ban.findtime=${FAIL2BAN_FINDTIME}"
      - "traefik.http.middlewares.fail2ban.plugin.fail2ban.bantime=${FAIL2BAN_BANTIME}"
    networks:
      - proxy

networks:
  proxy:
    external: true
